import { type MigrationInterface, type QueryRunner } from 'typeorm'

/**
 * Generated by `pnpm migration:generate --name=AddLotteryCodeRequestToken` — diff of the entities
 * against the current schema. Review before committing: generated diffs
 * describe structural changes, not data backfills (add those by hand).
 */
export class AddLotteryCodeRequestToken1789865497484 implements MigrationInterface {
  name = 'AddLotteryCodeRequestToken1789865497484'

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql)
  }
}

// 手工剔除生成器误判的 DROP INDEX uq_lottery_codes_activity_is_test：
// 该部分唯一索引（每活动至多一个测试码）由早期迁移建立，实体元数据不声明它，
// 生成 diff 会想删掉——保留原索引，本迁移只加 request_token 列。
const UP: string[] = ['ALTER TABLE "lottery_codes" ADD "request_token" character varying(64)']

const DOWN: string[] = ['ALTER TABLE "lottery_codes" DROP COLUMN "request_token"']
