import { type MigrationInterface, type QueryRunner } from 'typeorm'

/**
 * Generated by `pnpm migration:generate --name=AddAuditPrizeDescription` — diff of the entities
 * against the current schema. Review before committing: generated diffs
 * describe structural changes, not data backfills (add those by hand).
 */
export class AddAuditPrizeDescription1790338671470 implements MigrationInterface {
  name = 'AddAuditPrizeDescription1790338671470'

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const sql of UP) await queryRunner.query(sql)
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const sql of DOWN) await queryRunner.query(sql)
  }
}

const UP: string[] = [
  'ALTER TABLE "audit_logs" ADD "prize_description" character varying(500)',
  'ALTER TABLE "audit_logs" ADD "prize_id" integer',
  // —— 以下为手工追加的数据回填（结构由脚本生成，回填按其文件头指引补入）——
  // pass A：奖品还在——描述与 id 按 (activity_id, name) join 回填
  `UPDATE "audit_logs" a
     SET "prize_description" = p."description",
         "prize_id" = p."id"
    FROM "prizes" p
   WHERE p."activity_id" = a."activity_id"
     AND p."name" = a."prize_name"
     AND a."prize_id" IS NULL`,
  // pass B：奖品已删——经抽奖记录找回 id（描述无法恢复，id 是溯源指针）
  `UPDATE "audit_logs" a
     SET "prize_id" = r."prize_id"
    FROM "lottery_records" r
    JOIN "lottery_codes" c ON c."id" = r."lottery_code_id"
   WHERE c."activity_id" = a."activity_id"
     AND c."code" = a."lottery_code"
     AND r."prize_id" IS NOT NULL
     AND a."prize_id" IS NULL`,
]

const DOWN: string[] = [
  'ALTER TABLE "audit_logs" DROP COLUMN "prize_description"',
  'ALTER TABLE "audit_logs" DROP COLUMN "prize_id"',
]
